config/routes.rb
Topramenrecipes::Application.routes.draw do

  get "home/index"

resources :recipes
resources :categories

  root :to => 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :active, :title
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :estimated_time_to_make, :recipe, :title

validates_presence_of :title, :recipe, :estimated_time_to_make
validates_uniqueness_of :title, :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    if @category.save redirect_to @category, :notice => "Category created"
    else
      render :action => "new"
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category]) { redirect_to @category, :notice => "Category Updated"}
    else
      redirect_to :action => "new"
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(params[:recipe])
    if @recipe.save
      redirect_to @recipe, :notice => "New Recipe Created"
    else
      render :action => "new"
    end
  end

  def edit
  @recipe = Recipe.find(params[:id])
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(params[:recipe])
      redirect_to @recipe
    else
      render :action => "edit"
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories</h1>
<div>
<%= link_to "New Category", new_category_path %>
</div>
<div>
<% @category.each do |category| %>
<%= category.title %>
<% end  %>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= form_for @category do |f| -%>
  <%= f.label :title  %>
  <%= f.text_field :title %><br />
  <%= f.submit "New Category" %>
<% end -%>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/home/index.html.erb
<h1>Top Ramen Recipes</h1>
<%= link_to "Recipes", recipes_path %>
<p>Currently Under Production</p>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Topramenrecipes</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| -%>
<% if @recipe.errors.any? %>
<div id="errorExplanation">
	<h2><%= pluralize(@recipe.errors.count, "error") %> stopped this recipe from being saved</h2>

	<ul>
		<% @recipe.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end -%>
	</ul>
</div>
<% end -%>
<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title %><br />
 </div>
<div class="field">
  <%= f.label :recipe %>
 </div>
  <%= f.text_area :recipe %><br />
<div class="field">
  <%= f.label :estimated_time_to_make %>
  <%= f.text_area :estimated_time_to_make %>
 </div>
<div class="actions"> 
  <%= f.submit "Add New Recipe" %>
</div>
<% end -%>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render "form" %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>
<hr />
<%= link_to "New Recipe", new_recipe_path %>
<hr />
<% @recipes.each do |r| %>
<%= r.title %><br />
<%= r.recipe %><br />
<%= r.estimated_time_to_make %><br />
<%= link_to "Show", r %>
<%= link_to "Delete", r, :method => :delete, :confirm => "Are you sure" %>
<hr />
<% end -%>

app/views/recipes/new.html.erb
<%= render "form" %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @recipe.title %></h1>
<p><%= @recipe.recipe %></p>
<p><%= @recipe.estimated_time_to_make %></p>

<%= link_to "Back", recipes_path %><br />
<%= link_to "Edit", edit_recipe_path(@recipe) %>